### test 03 -> get a comment by id
GET http://localhost:3000/comments/111

### test 04 -> get a comment by musicId
GET http://localhost:3000/comments/music/12312423

### test 05 -> add a comment with id=111
POST http://localhost:3000/comments
Content-Type: application/json

{ "author":"622f6967476b268f715f1c5e", "music": "622f6a75b59e5486dee9d39a", "content": "good music"}

