### test 03 -> get a comment by id
GET http://localhost:3000/comments/622fb7b98cc64d80a7035c04

### test 04 -> get comments under a music
GET http://localhost:3000/comments/music/622f6ae1b59e5486dee9d39f

### test 05 -> add a comment
POST http://localhost:3000/comments
Content-Type: application/json

{ "author":"622f6967476b268f715f1c5d", "underMusic": "622f6ae1b59e5486dee9d39f", "content": "superb"}

