### test 01 -> get all favorites
GET http://localhost:3000/favorite

### test 02 -> add a favorite
POST http://localhost:3000/favorite
Content-Type: application/json

{"userId": "622f6967476b268f715f1c5d", "musicId": "622f6ae1b59e5486dee9d39f"}

### test 03 -> remove favorite
DELETE http://localhost:3000/favorite/622e4e2b79e6b372365b9eb8

### test 04 -> get favorite from user
GET http://localhost:3000/favorite/user/3

### test 05 -> get favorite from music
GET http://localhost:3000/favorite/music/2