### test 01 -> base url
GET http://localhost:3000/

### test 02 -> register a valid user
POST http://localhost:3000/users/register
Content-Type: application/json

{
	"username":"kyaw",
	"email":"kkyaw@gmail.com",
	"password":"plainpassword4",
	"firstname":"Kyaw",
	"lastname":"Thiha"
}

### test 03 -> login with a valid user
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "elias@gmail.com",
    "password": "plainpassword3"
}